### PR TITLE
Added ibaxa/cart package

### PR DESCRIPTION
**Pull request by mikadamczyk**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | N/A
| **Type**                                   | feature/bug/improvement
| **Target Ibexa version** | `v4.4` - please update `x` accordingly
| **BC breaks**                          | no
| **Doc needed**                       | no

This PR adds [ibexa/cart](https://github.com/ibexa/cart) package to Ibexa DXP Commerce.

#### Checklist:
- [ ] Provided PR description.
- [ ] Tested the solution manually.
- [ ] Checked that target branch is set correctly.
- [ ] Asked for a review (ping `@ibexa/engineering`).

### CODE REVIEW

**Review by mnocon — APPROVED** [review]
Thanks!

**Comment by webhdx** [comment]
@mnocon What has happened to CI? Says it was cancelled and some errors were found. Can we merge this PR?

**Comment by mnocon** [comment]
We can merge this, the cancel message says that the job took longer than 2 hours that we have set currently as maximum exeuction time

**Comment by adamwojs** [comment]
> We can merge this [...]

I could not resist :see_no_evil:

**Comment by mnocon** [comment]
I hope you have that big enter button prepared for situations like this 😄

**Pull request merged**
